name: Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  LinuxBuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12.4
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build Binary
      run: pyinstaller --onefile --name backpropagation main.py
    - name: Upload Binary
      uses: actions/upload-artifact@v4
      with:
        name: backpropagation
        path: dist/backpropagation
